/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatusTitle: typeof import('./src/components/custom/card-status-title/index.vue')['default']
    MbText: typeof import('./src/components/common/mb-text/index.vue')['default']
    PageContainer: typeof import('./src/components/common/page-container/index.vue')['default']
    RingCharts: typeof import('./src/components/custom/ring-charts/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
